FROM maven:3.6.3-jdk-8 AS test
COPY pom.xml /build/
COPY src /build/src/
WORKDIR /build
RUN mvn test

FROM maven:3.6.3-jdk-8 AS build
COPY --from=test /build /build
WORKDIR /build
RUN mvn package

FROM openjdk:8-jre
COPY --from=build /build/target/accenture-techhub-0.0.1-SNAPSHOT.war /app/
WORKDIR /app
EXPOSE 8080
CMD ["java", "-jar", "accenture-techhub-0.0.1-SNAPSHOT.war"]
